### PR TITLE
added demographics base models

### PR DESCRIPTION
**Pull request by ShahanM**
Added a domain object called Demographics and some constants for the front end form data.

### CODE REVIEW

**Comment by ShahanM** [comment]
Looks like I need to setup up my linter. I could use some help with that.

**Comment by karlhigley** [comment]
> Looks like I need to setup up my linter. I could use some help with that

@ShahanM You can do `pre-commit install` from the root of the repo to get the various linters and formatters set up

**Review by karlhigley — APPROVED** [review]
LGTM once the linter issues are fixed

**Comment by kluver** [comment]
Do we want to use pydanric enums: https://docs.pydantic.dev/2.0/usage/types/enums/ ?

**Comment by ShahanM** [comment]
@kluver maybe I will take a look into it (pydantic enum) after getting this merged.

**Pull request merged**
